apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dagster.fullname" . }}-instance
  labels:
    app: {{ template "dagster.name" . }}
    chart: {{ template "dagster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  dagster.yaml: |
    run_launcher:
      module: dagster_k8s.launcher
      class: K8sRunLauncher
      config:
        {{- with .Values.imagePullSecrets }}
        image_pull_secrets:
            {{- toYaml . | nindent 10 }}
        {{- end }}
        service_account_name: {{ include "dagster.serviceAccountName" . }}
        job_image: "{{ .Values.job_image }}"
        instance_config_map: "{{ template "dagster.fullname" .}}-instance"
        image_pull_policy: "{{ .Values.imagePullPolicy }}"
        job_namespace: "{{ .Release.Namespace }}"

    run_storage:
      module: dagster_postgres.run_storage
      class: PostgresRunStorage
      config:
        postgres_db:
          username: {{ .Values.postgresql.postgresqlUsername}}
          password: {{ .Values.postgresql.postgresqlPassword	}}
          hostname: {{ template "dagster.postgresql.fullname" . }}
          db_name:  {{ .Values.postgresql.postgresqlDatabase	}}
          port: {{ .Values.postgresql.service.port }}

    event_log_storage:
      module: dagster_postgres.event_log
      class: PostgresEventLogStorage
      config:
        postgres_db:
          username: {{ .Values.postgresql.postgresqlUsername}}
          password: {{ .Values.postgresql.postgresqlPassword	}}
          hostname: {{ template "dagster.postgresql.fullname" . }}
          db_name:  {{ .Values.postgresql.postgresqlDatabase	}}
          port: {{ .Values.postgresql.service.port }}
