version: "3.7"

services:
  test-rabbitmq:
    image: rabbitmq:3.8.2
    container_name: test-rabbitmq
    ports:
      - "5672:5672"
    networks:
      - rabbitmq

networks:
  rabbitmq:
    driver: bridge
    name: rabbitmq
