version: '3.7'

services:
  test-event-log-storage-db:
    image: postgres:11
    container_name: test-event-log-storage-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_USER: "test"
      POSTGRES_DB: "test"
    networks:
      - postgres_multi

  test-run-storage-db:
    image: postgres:11
    container_name: test-run-storage-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_USER: "test"
      POSTGRES_DB: "test"
    networks:
      - postgres_multi

networks:
  postgres_multi:
    driver: bridge
    name: postgres_multi
